import "../app/styles/globals.css";

import Navbar from "../app/components/NavBar/navBar";
import Footer from "../app/components/Footer";

import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>


          <Navbar />
          <main>{children}</main>
          {/* <Footer /> */}

        </Providers>
      </body>
    </html>
  );
}
